<?php
session_start();
include 'config.php';

if(!isset($_SESSION['username']) && !isset($_SESSION['clientID']))
{
    header("Location: UserLogin.php");
    exit();
}

if(!isset($_GET['id']))
{
    echo "No report selected.";
    exit();
}

$reportID = mysqli_real_escape_string($conn, $_GET['id']);

$query = mysqli_query($conn,
"SELECT
    fr.*,
    p.ProjectName,
    p.Place,
    p.StartDate,
    p.EndDate,
    p.ClientID,
    p.StaffID AS ProjectStaffID,
    c.ClientCompany,
    s.Username AS EngineerName
 FROM final_report fr
 INNER JOIN project p
 ON fr.ProjectID = p.ProjectID
 LEFT JOIN client c
 ON p.ClientID = c.ClientID
 LEFT JOIN staff s
 ON fr.StaffID = s.StaffID
 WHERE fr.ReportID='$reportID'");

if(mysqli_num_rows($query) == 0)
{
    echo "Report not found.";
    exit();
}

$report = mysqli_fetch_assoc($query);

/* AUTHORIZATION - only Admin/Boss, the client who owns the project,
   or an engineer assigned to it may view this report */
$authorized = false;
$role = $_SESSION['role'] ?? null;

if($role === 'Admin' || $role === 'Boss')
{
    $authorized = true;
}
elseif($role === 'Client' && isset($_SESSION['clientID']))
{
    $authorized = ((int)$report['ClientID'] === (int)$_SESSION['clientID']);
}
elseif($role === 'Engineer' && isset($_SESSION['username']))
{
    $staffCheck = mysqli_fetch_assoc(mysqli_query($conn,
        "SELECT StaffID FROM staff WHERE Username='" . mysqli_real_escape_string($conn, $_SESSION['username']) . "'"));
    $myStaffID = $staffCheck['StaffID'] ?? 0;

    $assignCheck = mysqli_fetch_assoc(mysqli_query($conn,
        "SELECT 1 FROM project_assignment WHERE ProjectID='" . (int)$report['ProjectID'] . "' AND StaffID='" . (int)$myStaffID . "'"));

    $authorized = ((int)$report['ProjectStaffID'] === (int)$myStaffID) || $assignCheck;
}

if(!$authorized)
{
    echo "You are not authorized to view this report.";
    exit();
}
?>

<!DOCTYPE html>
<html>
<head>
<title>View Final Report</title>

<style>
body{
    background:#f4f6fa;
    margin:0;
    font-family:'Segoe UI',Arial,sans-serif;
    color:#333;
}

.report-container{
    max-width:1000px;
    margin:40px auto;
    background:white;
    padding:50px;
    border-radius:20px;
    box-shadow:0 10px 30px rgba(0,0,0,0.15);
}

.header{
    text-align:center;
    border-bottom:3px solid #003366;
    padding-bottom:20px;
    margin-bottom:30px;
}

.header h1{
    color:#003366;
    margin-bottom:5px;
}

.header p{
    color:#666;
    margin:0;
}

.section{
    margin-bottom:30px;
}

.section h2{
    color:#003366;
    border-bottom:1px solid #ddd;
    padding-bottom:8px;
    margin-bottom:15px;
}

.info-table{
    width:100%;
    border-collapse:collapse;
}

.info-table td{
    padding:12px;
    border:1px solid #ddd;
}

.info-table .label{
    width:30%;
    background:#f2f2f2;
    font-weight:bold;
    color:#003366;
}

.content-box{
    line-height:1.7;
    white-space:pre-line;
    background:#f8f9fa;
    padding:20px;
    border-left:5px solid #003366;
    border-radius:10px;
}

.btn-area{
    text-align:right;
    margin-bottom:20px;
}

.btn{
    background:#003366;
    color:white;
    padding:10px 20px;
    border-radius:8px;
    text-decoration:none;
    font-weight:bold;
    border:none;
    cursor:pointer;
}

.btn:hover{
    background:#004aad;
}

@media print{
    .btn-area{
        display:none;
    }

    body{
        background:white;
    }

    .report-container{
        box-shadow:none;
        margin:0;
        border-radius:0;
        max-width:100%;
    }
}
</style>
</head>

<body>

<div class="report-container">

<div class="btn-area">
<button onclick="window.print()" class="btn">Print / Save as PDF</button>
<a href="FinalReport.php" class="btn">Back</a>
</div>

<div class="header">
<h1>Final Construction Project Report</h1>
<p>Generated by Engineer Helper System</p>
</div>

<div class="section">
<h2>1. Project Information</h2>

<table class="info-table">

<tr>
<td class="label">Project Name</td>
<td><?php echo htmlspecialchars($report['ProjectName']); ?></td>
</tr>

<tr>
<td class="label">Project Location</td>
<td><?php echo htmlspecialchars($report['Place']); ?></td>
</tr>

<tr>
<td class="label">Project Duration</td>
<td><?php echo $report['StartDate']; ?> to <?php echo $report['EndDate']; ?></td>
</tr>

<tr>
<td class="label">Project Manager</td>
<td><?php echo htmlspecialchars($report['ProjectManager']); ?></td>
</tr>

<tr>
<td class="label">Contractor</td>
<td><?php echo htmlspecialchars($report['Contractor']); ?></td>
</tr>

<tr>
<td class="label">Client Company</td>
<td><?php echo htmlspecialchars($report['ClientCompany']); ?></td>
</tr>

<tr>
<td class="label">Prepared By</td>
<td><?php echo htmlspecialchars($report['EngineerName']); ?></td>
</tr>

<tr>
<td class="label">Generated Date</td>
<td><?php echo $report['GeneratedDate']; ?></td>
</tr>

</table>
</div>

<div class="section">
<h2>2. Objective</h2>
<div class="content-box">
<?php echo htmlspecialchars($report['Objective']); ?>
</div>
</div>

<div class="section">
<h2>3. Budget and Cost Details</h2>

<table class="info-table">

<tr>
<td class="label">Original Budget</td>
<td>RM <?php echo number_format($report['OriginalBudget'],2); ?></td>
</tr>

<tr>
<td class="label">Final Cost</td>
<td>RM <?php echo number_format($report['FinalCost'],2); ?></td>
</tr>

<tr>
<td class="label">Cost Variance</td>
<td><?php echo nl2br(htmlspecialchars($report['CostVariance'])); ?></td>
</tr>

</table>
</div>

<div class="section">
<h2>4. Planning and Design</h2>
<div class="content-box">
<?php echo htmlspecialchars($report['PlanningDesign']); ?>
</div>
</div>

<div class="section">
<h2>5. Inspection and Testing</h2>
<div class="content-box">
<?php echo htmlspecialchars($report['InspectionTesting']); ?>
</div>
</div>

<div class="section">
<h2>6. Declaration</h2>
<div class="content-box">
This final report has been reviewed and recorded in the Engineer Helper system for project documentation and client reference.
</div>
</div>

</div>

</body>
</html>